Adicionada classe de erro que estava faltando
vindi/vindi-ruby pull request #9
Opened 2019-04-23 12:25 UTC by rainerborene

2019-04-23 16:14 UTC, laerte-guimaraes requested changes

2019-04-23 16:14 UTC, laerte-guimaraes commented on vindi.gemspec
> +  spec.add_dependency 'faraday', ['>= 0.13', '< 1.0']
@rainerborene Boa tarde!
Infelizmente, essa alteração não faz parte desse PR;
Poderia removê-la?

2019-04-23 16:29 UTC, rainerborene commented
@laerte-guimaraes alteração feita.

2019-04-23 16:29 UTC, rainerborene commented on vindi.gemspec
> +  spec.add_dependency 'faraday', ['>= 0.13', '< 1.0']
alteração feita.

2019-04-23 16:44 UTC, vitorkusiaki commented
@rainerborene qual o objetivo desse PR? Consegue descrever melhor o que te motivou a colocar esse código e os erros que tem recebido?

2019-04-23 16:47 UTC, rainerborene commented
@vitorkusiaki enquanto estava escrevendo testes disparando requisições com dados inválidos, os erros eram específicos dessa classe inexistente.

2019-04-23 16:59 UTC, vitorkusiaki commented
@rainerborene pode dar um exemplo de requisição que enviou e que gerou erro 500?

2019-04-23 17:02 UTC, rainerborene commented
@vitorkusiaki não me lembro agora.

2019-04-23 17:14 UTC, vitorkusiaki commented
Preciso conseguir simular esse erro pra dar continuidade no PR. Aguardo uma requisição que reproduza o cenário

2019-04-23 18:16 UTC, rainerborene commented
Há uma referência no código para uma classe inexistente. Remova isso então.

On Tue, Apr 23, 2019, 14:14 Vitor Kusiaki <notifications@github.com> wrote:

> Preciso conseguir simular esse erro pra dar continuidade no PR. Aguardo
> uma requisição que reproduza o cenário
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/vindi/vindi-ruby/pull/9#issuecomment-485893945>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAAYY7NNFXDT7R3PGAQA7N3PR47XNANCNFSM4HHXN7BA>
> .
>

2019-04-23 23:54 UTC, laerte-guimaraes approved these changes

2019-04-24 14:07 UTC, vitorkusiaki approved these changes

2019-04-24 16:11 UTC, merged